pipeline:
  name: harnessDeploycodepipeline
  identifier: harnessDeploycodepipeline
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: testinglambdacloudformation
        build: <+input>
  stages:
    - stage:
        name: Git
        identifier: Git
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: zip -9 Lambda.zip Lambda.yaml
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: "aws configure set aws_access_key_id AKIA5U3R675QNZZ2AJET\r\naws configure set aws_secret_access_key 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\r\naws s3 cp Lambda.zip s3://mytestlambdas3code/\r\n#aws s3 cp InfraCodepipeline.yml s3://mytestlambdas3code/"
