pipeline:
  name: harnessDeploycodepipeline
  identifier: harnessDeploycodepipeline
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: testinglambdacloudformation
        build: <+input>
  stages:
    - stage:
        name: Git
        identifier: Git
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: "ls -lsa\r\n#zip -9 lambda.zip /testinglambdacloudformation/*\r\n"
